### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by miker177** [juanferrer/sdlc#1]
Hello, I don't know where to post this.  
I noticed some issues with the roll tables and in the bestiary. For the roll table, I have noticed that every time you posted an update, the things in the roll table are duplicated (Compendium Packs)

Example: Academic Professions Rolltable:
1. Architecture
1. Architecture
1. Architecture
1. Architecture
1. Architecture
2. Astrology
2. Astrology
etc.
![image](https://github.com/juanferrer/sdlc/assets/107895781/26ef2186-fd61-48c4-8642-0068c4b73413)

I noticed this on all roll tables. 
And in the Core Bestiary document, when you go to the character templates, stuff is missing from the templates, especially a Warrior and Rogue.
![image](https://github.com/juanferrer/sdlc/assets/107895781/d3d43c62-3d55-4182-9ea4-286bc1ab8616)

**Comment by juanferrer** [comment]
This is the right place to post it, thanks. You can also do it in the [#module-bug-reports channel](https://discord.com/channels/746874576666886226/1092831179088072725) of the [Discord server](https://discord.gg/rVkk2xKk). I'll get it fixed, though.

**Comment by juanferrer** [comment]
This has been fixed, coming in the next version.
