### ISSUE TITLE
Clockwork Purpose rollable table is wrong.

### ISSUE THREAD

**Issue by redredkrovy** [juanferrer/sdlc#2]
Just playing around and creating a clockwork I noticed the Clockwork Purpose rollable table is a copy of the Clockwork Form rollable table.  Also is it possible to create a macro that does all of the roles for your ancestry and inputs the results into your "description" tab automatically?

**Comment by juanferrer** [comment]
Ah, well spotted! I've fixed it now. Releasing an update soon.
The macro... it's a good idea, but with so many other things to do, it becomes very low priority.
