### ISSUE TITLE
getting Error about sdlc-1001 being forbidden when trying to update modules

### ISSUE THREAD

**Issue by sirkerry** [juanferrer/sdlc#4]
Error: [sdlc-1001] Access to module manifest at https://foundryprotectedcontentdistributionapi.azurewebsites.net/api/manifest/sdlc-1001 is forbidden
    at Setup.post (setup.js:9206:21)
    at async #updateCheck (setup.js:6306:24)
    at async update (setup.js:6082:23)

this is in Version 12 Build 331 of FVTT

**Comment by juanferrer** [comment]
Fixed now.
